### ISSUE TITLE
unexpected error occured

### ISSUE THREAD

**Issue by LazilyKen** [null2264/yokai#278]
### Steps to reproduce

1. opened the app
2. an unexpected error occured op up

### Expected behavior

open the app like normal but instead got into an unexpected error

### Actual behavior

an unexpected error occured 

### Crash logs

App version: 1.9.0-b3 (standard, 31773876b4, 150, 2024-12-03T09:44:02Z)
Android version: 14 (SDK 34)
Android build ID: X6871-H962CF-U-OP-240929V2354
Device brand: Infinix
Device manufacturer: INFINIX
Device name: Infinix-X6871
Device model: Infinix X6871
Device product name: X6871-OP

java.lang.Throwable: java.lang.RuntimeException: Canvas: trying to draw too large(122792960bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at coil3.transition.CrossfadeDrawable.draw(SourceFile:134)
	at android.widget.ImageView.onDraw(ImageView.java:1446)
	at android.view.View.draw(View.java:24021)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:31)
	at android.view.View.draw(View.java:24028)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.draw(View.java:24028)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:31)
	at android.view.View.draw(View.java:24028)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at androidx.recyclerview.widget.RecyclerView.drawChild(SourceFile:1)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.draw(View.java:24028)
	at androidx.recyclerview.widget.RecyclerView.draw(SourceFile:2)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.draw(View.java:24028)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(SourceFile:138)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.draw(View.java:24028)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:31)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.updateDisplayListIfDirty(View.java:22839)
	at android.view.View.draw(View.java:23738)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
	at android.view.View.draw(View.java:24028)
	at com.android.internal.policy.DecorView.draw(DecorView.java:832)
	at android.view.View.updateDisplayListIfDirty(View.java:22848)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:707)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:713)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:811)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5223)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4915)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4039)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2644)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9812)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1508)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1517)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1085)
	at android.view.Choreographer.doFrame(Choreographer.java:977)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1491)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:243)
	at android.os.Looper.loop(Looper.java:338)
	at android.app.ActivityThread.main(ActivityThread.java:8472)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

--------- beginning of system
12-06 15:42:39.614  9548  9548 E ActivityThread: processDualLinkMonitor exception java.lang.SecurityException: Settings key: <wifi_dual_station> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
12-06 15:42:45.951  9548  9548 E ActivityThread: processDualLinkMonitor exception java.lang.SecurityException: Settings key: <wifi_dual_station> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
12-06 15:42:47.814  9548  9548 E ActivityThread: processDualLinkMonitor exception java.lang.SecurityException: Settings key: <wifi_dual_station> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
12-06 15:43:36.844  9548  9548 E ActivityThread: processDualLinkMonitor exception java.lang.SecurityException: Settings key: <wifi_dual_station> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
12-06 15:43:53.293 11690 11690 E ActivityThread: processDualLinkMonitor exception java.lang.SecurityException: Settings key: <wifi_dual_station> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
--------- beginning of crash
12-06 15:43:55.671 11690 11690 E AndroidRuntime: FATAL EXCEPTION: main
12-06 15:43:55.671 11690 11690 E AndroidRuntime: Process: eu.kanade.tachiyomi.yokai, PID: 11690
12-06 15:43:55.671 11690 11690 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to draw too large(122792960bytes) bitmap.
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at coil3.transition.CrossfadeDrawable.draw(SourceFile:134)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.widget.ImageView.onDraw(ImageView.java:1446)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24021)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:31)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24028)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24028)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:31)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24028)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.drawChild(SourceFile:1)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24028)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.draw(SourceFile:2)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24028)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(SourceFile:138)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24028)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(SourceFile:31)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22839)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:23738)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:4648)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4409)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.draw(View.java:24028)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:832)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22848)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:707)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:713)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:811)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5223)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4915)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4039)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2644)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9812)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1508)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1517)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:1085)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:977)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1491)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:243)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:338)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8472)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
12-06 15:43:55.671 11690 11690 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
12-06 15:43:56.559 16014 16014 E ActivityThread: processDualLinkMonitor exception java.lang.SecurityException: Settings key: <wifi_dual_station> is not readable. From S+, settings keys annotated with @hide are restricted to system_server and system apps only, unless they are annotated with @Readable.
12-06 15:43:57.937 16750 16750 E TranChoreographerImpl: skippedFrames: 41
12-06 15:44:02.753 16750 16750 E ActivityThread: processDualLinkMonitor exception java.lang.SecurityException: Settings key: <wi

### Yōkai version

1.9.0-b3

### Android version

Android 14

### Device

Infinix GT 20 Pro 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.5.13](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by null2264** [comment]
Update to [Beta 4](https://github.com/null2264/yokai/releases/tag/v1.9.0-b4)
