### ISSUE TITLE
Yokai not deleting read chapters

### ISSUE THREAD

**Issue by fedex-bermu** [null2264/yokai#316]
### Steps to reproduce

1 have yokai download several chapters
2 read said chapters

### Expected behavior

Read chapters should get deleted when they are finished

### Actual behavior

Randomly some of them get deleted and some not

### Yōkai version

App version: 1.9.6 (standard, 6c40fe92be, 156, 2024-12-17T23:11:43Z)

### Android version

Android version: 14 (SDK 34)

### Device

Samsung SM-S918B (dm3q)

### Other details

Save as CBZ archive is on
Auto-append ID is on
Remove when marked as read is on
Remove after read is "second to last chapter"

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.9.6](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have filled out all of the requested information in this form.

**Comment by fedex-bermu** [comment]
Also to add, I've had some crashes lately this is the log: 

`
App version: 1.9.7 (standard, f8e7002a9b, 157, 2024-12-22T23:26:07Z)
Android version: 14 (SDK 34)
Android build ID: UP1A.231005.007.S918BXXU7CXK4
Device brand: samsung
Device manufacturer: samsung
Device name: dm3q
Device model: SM-S918B
Device product name: dm3qxxx



java.lang.Throwable: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e8c4ddd u0 eu.kanade.tachiyomi.yokai/androidx.work.impl.foreground.SystemForegroundService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2323)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2294)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2619)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:9063)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)


--------- beginning of crash
12-29 11:10:18.891 18570 18570 E AndroidRuntime: FATAL EXCEPTION: main
12-29 11:10:18.891 18570 18570 E AndroidRuntime: Process: eu.kanade.tachiyomi.yokai, PID: 18570
12-29 11:10:18.891 18570 18570 E AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e8c4ddd u0 eu.kanade.tachiyomi.yokai/androidx.work.impl.foreground.SystemForegroundService}
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2323)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2294)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2619)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9063)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
--------- beginning of main
12-29 11:32:46.880  8569  8569 E tachiyomi.yokai: Not starting debugger since process cannot load the jdwp agent.
12-29 11:32:46.959  8593  8593 E i:error_handler: Not starting debugger since process cannot load the jdwp agent.
12-29 11:32:47.017  8569  8623 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f.
12-29 11:32:47.018  8569  8623 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f.
12-29 11:32:47.307  8593  8652 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
`

**Comment by null2264** [comment]
That crash is *probably* unrelated, it's a bug that Google refuses to fix and Smasnug's power management system amplifies the effect, I recommend trying out https://dontkillmyapp.com/samsung if you haven't.

Also, can you dump the log whenever a chapter is not being deleted?

**Comment by fedex-bermu** [comment]
Thanks for the reply about the power management. Here's a log about a chapter not being deleted.

App version: 1.9.7 (standard, f8e7002a9b, 157, 2024-12-22T23:26:07Z)
Android version: 14 (SDK 34)
Android build ID: UP1A.231005.007.S918BXXU7CXK4
Device brand: samsung
Device manufacturer: samsung
Device name: dm3q
Device model: SM-S918B
Device product name: dm3qxxx



--------- beginning of crash
12-29 11:10:18.891 18570 18570 E AndroidRuntime: FATAL EXCEPTION: main
12-29 11:10:18.891 18570 18570 E AndroidRuntime: Process: eu.kanade.tachiyomi.yokai, PID: 18570
12-29 11:10:18.891 18570 18570 E AndroidRuntime: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{e8c4ddd u0 eu.kanade.tachiyomi.yokai/androidx.work.impl.foreground.SystemForegroundService}
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2323)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2294)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2619)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:9063)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
12-29 11:10:18.891 18570 18570 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
--------- beginning of main
12-29 21:56:39.594 25164 25238 E SQLiteLog: (284) automatic index on unread(manga_id)
12-29 21:56:39.594 25164 25238 E SQLiteLog: (284) automatic index on M(_id)
12-29 21:56:39.594 25164 25238 E SQLiteLog: (284) automatic index on split(_id)
12-29 21:56:39.595 25164 25238 E SQLiteLog: (284) automatic index on split(_id)
12-29 21:56:39.951 25164 25220 E SQLiteLog: (284) automatic index on S(manga_id)
12-29 21:56:39.952 25164 25220 E SQLiteLog: (284) automatic index on C(manga_id)
12-29 21:56:39.952 25164 25220 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-29 21:56:40.011 25164 25238 E SQLiteLog: (284) automatic index on split(_id)
12-29 22:01:34.518 25164 25239 E Yokai   : Extension package is not found (io.github.mthli.loglog)
12-29 22:02:34.558  3057  3057 E tachiyomi.yokai: Not starting debugger since process cannot load the jdwp agent.
12-29 22:02:34.719  3057  3103 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f.
12-29 22:02:34.719  3057  3103 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f.
12-29 22:02:34.910  3057  3102 E SQLiteLog: (283) recovered 1 frames from WAL file /data/data/eu.kanade.tachiyomi.yokai/databases/tachiyomi.db-wal
12-29 22:02:34.940  3057  3184 E chromium: [1229/220234.939982:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
12-29 22:02:35.181  3057  3146 E SQLiteLog: (284) automatic index on S(manga_id)
12-29 22:02:35.181  3057  3146 E SQLiteLog: (284) automatic index on C(manga_id)
12-29 22:02:35.181  3057  3146 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-29 22:02:36.125  3057  3166 E SQLiteLog: (284) automatic index on unread(manga_id)
12-29 22:02:36.126  3057  3166 E SQLiteLog: (284) automatic index on M(_id)
12-29 22:02:36.126  3057  3166 E SQLiteLog: (284) automatic index on split(_id)
12-29 22:02:36.126  3057  3166 E SQLiteLog: (284) automatic index on split(_id)
12-29 22:03:06.670  4504  4504 E tachiyomi.yokai: Not starting debugger since process cannot load the jdwp agent.
12-29 22:03:06.814  4504  4633 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f.
12-29 22:03:06.814  4504  4633 E tachiyomi.yokai: No package ID 76 found for resource ID 0x760b000f.
12-29 22:03:06.959  4504  4624 E SQLiteLog: (283) recovered 1 frames from WAL file /data/data/eu.kanade.tachiyomi.yokai/databases/tachiyomi.db-wal
12-29 22:03:06.991  4504  4752 E chromium: [1229/220306.991121:ERROR:variations_seed_loader.cc(39)] Seed missing signature.
12-29 22:03:07.175  4504  4737 E SQLiteLog: (284) automatic index on S(manga_id)
12-29 22:03:07.175  4504  4737 E SQLiteLog: (284) automatic index on C(manga_id)
12-29 22:03:07.175  4504  4737 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
12-29 22:03:13.451  4504  4743 E SQLiteLog: (284) automatic index on split(_id)
12-29 22:03:13.496  4504  4662 E FrameEvents: updateAcquireFence: Did not find frame.
12-29 22:03:13.502  4504  4743 E SQLiteLog: (284) automatic index on unread(manga_id)
12-29 22:03:13.503  4504  4743 E SQLiteLog: (284) automatic index on M(_id)
12-29 22:03:13.503  4504  4743 E SQLiteLog: (284) automatic index on split(_id)
12-29 22:03:13.503  4504  4743 E SQLiteLog: (284) automatic index on split(_id)
12-29 22:03:13.603  4504  4743 E SQLiteLog: (284) automatic index on split(_id)
12-29 22:10:19.436  4504  4662 E FrameEvents: updateAcquireFence: Did not find frame.

**Comment by fedex-bermu** [comment]
Also looking at the log at the root folder this is what appears (I only copied the lasts ones):

2024-12-29 22:09:12.730 Debug: (Yokai) onPageSelected: 27/32
2024-12-29 22:09:22.372 Debug: (Yokai) onPageSelected: 28/32
2024-12-29 22:09:22.373 Debug: (Yokai) Request preload next chapter because we're at page 28 of 32
2024-12-29 22:09:34.865 Debug: (Yokai) onPageSelected: 29/32
2024-12-29 22:09:34.866 Debug: (Yokai) Request preload next chapter because we're at page 29 of 32
2024-12-29 22:09:49.633 Debug: (Yokai) onPageSelected: 30/32
2024-12-29 22:09:49.633 Debug: (Yokai) Request preload next chapter because we're at page 30 of 32
2024-12-29 22:09:59.618 Debug: (Yokai) onPageSelected: 31/32
2024-12-29 22:09:59.619 Debug: (Yokai) Request preload next chapter because we're at page 31 of 32
2024-12-29 22:10:17.104 Debug: (Yokai) onPageSelected: 32/32
2024-12-29 22:10:17.112 Debug: (Yokai) Request preload next chapter because we're at page 32 of 32
2024-12-29 22:10:17.535 Debug: (Yokai) onTransitionSelected: Next(from=/comic/cjee7NwJ/Onzid8x_-chapter-58-en, to=null)
2024-12-29 22:10:19.360 Debug: (Yokai) Recycling chapter Chapter 58

**Comment by null2264** [comment]
There's nothing unfortunately... I couldn't replicate it either...

**Comment by fedex-bermu** [comment]
Ok, I've been trying different things and it seems that since I have disabled the "save as CBZ archive" option it's not happening anymore. Maybe you could try with that option on and see if you could replicate it

**Comment by null2264** [comment]
I always have it on, is disabling only "Auto-append ID" doesn't fix it?

**Comment by fedex-bermu** [comment]
Sorry for the delay in the response. Yeah it's still happening, doesn't matter if auto append ID is on or off,  CBZ on or off neither.
Still having some crashes when updating the library (will attach the logs), tried having yokai not restricted on battery optimization, and force always keep open.
Also having defects while reading.
![Screenshot_20250106_195351_Ykai](https://github.com/user-attachments/assets/09683d09-e105-4d5d-9465-d304c9f5eba9)
![Screenshot_20250106_195435_Ykai](https://github.com/user-attachments/assets/fc0b5940-313e-49a6-a514-636a760cceb0)
And lastly, I think that the problem with the chapters not being deleted appropriately has something to do with a problem I keep having that is that it seems it cannot remember my position while reading, if I'm for example in the middle of a chapter, and switch to other app, when I come back, doesn't matter if the been 30 seconds or 3 hours, it takes me back to some previous position, it can be some chapters back or maybe the start of the same chapter, it seems random.
I said it seems related with the problem of the title because if I read for ex 10 chapters continuously, they are deleted flawlessly when I finish reading them, the problem is when I switch mid chapter and then continue, that's seems to be when it doesn't delete that chapter when it's finished, it's like yokai lost the reading position for that chapter. 
All this problems are new, even with nightly builds, everything worked perfect on my end, something changed in the latest updates of the app. 
Tell me how can I help you, if you need me to use a debugging build I have no problem. 

Thanks in advance and sorry for the lengthy post.
